create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null check (category in ('women', 'men', 'unisex', 'tester', 'gift')),
  collection text not null default '',
  badge text not null default 'New',
  discount text,
  old_price text,
  price text not null,
  size text not null,
  description text not null,
  notes text[] not null default '{}',
  image_url text not null,
  whatsapp_text text not null,
  featured boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read active products" on public.products;

create policy "Public can read active products"
on public.products
for select
using (is_active = true);
